name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions: read-all|write-all
#  actions: write
#  checks: write
#  contents: write
#  deployments: write
#  id-token: write
#  issues: write
#  discussions: write
#  packages: write
#  pages: write
#  pull-requests: write
#  repository-projects: write
#  security-events: write
#  statuses: write
# Deploy to the github-pages environment
environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}
jobs:
  Playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: github-pages/
          retention-days: 30
      - name: Publish HTML report
        id: deployment
        uses: actions/deploy-pages@v1.2.4
#        uses: PavanMudigonda/html-reporter-github-pages/composite@v1.1
#        with:
#          test_results: playwright-report
#          keep_reports: 20
